power_onset_perhead_vr_lfo = mnehelp.band_power(power_onset_perhead_vr, lfo_bands)
power_stop_perhead_vr_lfo = mnehelp.band_power(power_stop_perhead_vr, lfo_bands)

power_trials_onset_perhead_vr_lfo = mnehelp.band_power(power_trials_onset_perhead_vr, lfo_bands)
power_trials_stop_perhead_vr_lfo = mnehelp.band_power(power_trials_stop_perhead_vr, lfo_bands)

power_point_perhead_vr_ego_lfo = mnehelp.band_power(power_point_perhead_vr_ego, lfo_bands)
power_point_perhead_vr_allo_lfo = mnehelp.band_power(power_point_perhead_vr_allo, lfo_bands)

power_trial_point_perhead_vr_ego_lfo = mnehelp.band_power(power_trials_point_perhead_ego, lfo_bands)
power_trial_point_perhead_vr_allo_lfo = mnehelp.band_power(power_trials_point_perhead_allo, lfo_bands)

power_point_perhead_vr_ego_lfo = mnehelp.band_power(power_point_perhead_vr_ego, lfo_bands)
power_point_perhead_vr_allo_lfo = mnehelp.band_power(power_point_perhead_vr_allo, lfo_bands)

power_trial_point_start_perhead_hip_vr_ego_lfo = mnehelp.band_power(power_trials_point_perhead_ego, lfo_bands)
power_trial_point_start_perhead_hip_vr_allo_lfo = mnehelp.band_power(power_trials_point_perhead_allo, lfo_bands)